DROP DATABASE IF EXISTS todo_db;

CREATE DATABASE todo_db;

USE todo_db;

CREATE TABLE todo (
id int NOT NULL AUTO_INCREMENT,
item VARCHAR(50)NOT NULL,
completed BOOLEAN NOT NULL DEFAULT 0,
date TIMESTAMP,
PRIMARY KEY (id)
);